### ISSUE TITLE
Homebrew Formula?

### ISSUE THREAD

**Issue by parkr** [tj/histo#12]
Hey! This is gorgeous and amazing. Thoughts on a formula for homebrew?

Something like this:

``` ruby
require 'formula'

class Histo < Formula
  homepage 'https://github.com/visionmedia/histo'
  url 'https://github.com/visionmedia/histo/tarball/0.0.1'
  sha1 '3398f6d94bdbdb6f0112e77b61d9c2d6ae1facd1'

  def install
    system "make install"
  end
end
```

**Comment by tj** [comment]
looks good to me! I think anyone can fork homebrew to add it, not sure I've never added anything

**Comment by tj** [comment]
it would be nicer to install from master or something, I think brew is pretty bad with variable versions, otherwise they get outdated really quickly, probably not worth adding it at that point

**Comment by parkr** [comment]
What do you mean, "brew is pretty bad with variable versions"? If something has been updated, the `sha1` value will change.

**Comment by tj** [comment]
i mean like we have to change `https://github.com/visionmedia/histo/tarball/0.0.1` each release AFAIK

**Comment by parkr** [comment]
Yeah that's no problemo. If you clone the repo and do `bin/brew create https://github.com/visionmedia/histo/tarball/0.0.1` it creates that for you, `sha1` and everything. PRs are super easy and quickly accepted. Homebrew is a well-loved OSS project :)

**Comment by tzz** [comment]
I'd love to see the formula in Homebrew by default.

**Comment by tj** [comment]
definitely widely adopted but a bit of a mess IMO
