### ISSUE TITLE
Terminal messed up

### ISSUE THREAD

**Issue by hmeerlo** [tj/histo#8]
Hi, I like the idea of histo very much, although I can't get it to work properly. It only outputs weird characters on my terminals (iTerm2). Like this:

2;20;f█-53;20;f█-54;20;f█-55;20;f█-56;20;f█-57;20;f█-58;20;f█-59;20;f█

Any idea what is wrong?

**Comment by emilsoman** [comment]
I get the same output on Ubuntu 12.04 terminal

**Comment by jpmens** [comment]
Works on OS/X Terminal.app but not with iTerm2.
Also not if I set TERM=xterm-256color in the latter.

**Comment by miku** [comment]
Cute tool! However, I have the same scrambled output in iTerm2, although the coloring seems to work, just the `term_move_*` gets confused. Is there any argument against using curses' [move](http://pubs.opengroup.org/onlinepubs/7908799/xcurses/move.html)?

**Comment by rogeriopvl** [comment]
I also have the same garbled output using iterm2. Any setting I missing?

**Comment by jdanbrown** [comment]
+1 Garbled output in iTerm2, correct output in Terminal.app.

Also messed up from within tmux or screen, even with `TERM=xterm-256color`.

![Screen Shot 2013-02-07 at 11 02 01 AM](https://f.cloud.github.com/assets/627486/136132/5e305770-7140-11e2-85a3-daa609658ac2.png)

**Comment by pearkes** [comment]
Same issue on OS X 10.8.2, iTerm2 Build 1.0.0.20120724.

This is what the output looks like:

![Screen Shot 2013-02-07 at 10 52 51 AM](https://f.cloud.github.com/assets/846194/136820/b4c09462-7157-11e2-8a56-7958bcff5478.png)

**Comment by RhysU** [comment]
Ditto on a Fedora-based distro on either gnome-terminal or plain ol' xterm.

**Comment by livibetter** [comment]
The casue seems to be the positions of Y, which are negatives (is negative number expected?). I print out the positions with

``` c
printf("%d,%d\n", sx + x * xbarw, y - 1 - h + ypad);
```

and got same results in both urxvt and urxvt+tmux:

```
8,-3
8,-4
8,-5
[...]
```

I am guessing, other terminal would automatically `abs()` the negative position in `\e[y;x;f`, but tmux doesn't. So I changed the `term_move_to` to

```
term_move_to(sx + x * xbarw, abs(y - 1 - h + ypad));
```

and it can print the normal chart in tmux.

**Comment by tj** [comment]
I suppose I should have tried iterm2 :D I like the font rendering better in Terminal so I haven't been able to make myself use iterm2 yet, I'll try and patch this up soon

**Comment by jpmens** [comment]
@livibetter: that works, thanks.

**Comment by michaelhood** [comment]
@livibetter: thanks for that, fixes it in iTerm2 here.

**Comment by g5pw** [comment]
Yes, I can confirm it works. If you make a new release for the fix, @visionmedia , I'll commit it to MacPorts! ;)

**Comment by tj** [comment]
![Screen Shot 2013-03-11 at 8 52 50 AM](https://f.cloud.github.com/assets/25254/244347/02acd102-8a64-11e2-8290-7adc4bf89097.png)

**Comment by michaelmior** [comment]
I'm still getting something like the above in gnome-terminal on Ubuntu 12.04.
